name = "comment-system-worker"
main = "src/worker/index.js"
compatibility_date = "2024-10-01"

[vars]
TURNSTILE_SECRET_KEY = "你的Turnstile Secret Key"
DEFAULT_TURNSTILE_SITE_KEY = "你的默认Turnstile Site Key"
ADMIN_PASSWORD = "你的管理员密码"

[site]
bucket = "./src/admin"

[[kv_namespaces]]
binding = "SESSIONS"
id = "sessions_kv_namespace_id"

[[d1_databases]]
binding = "DB"
database_name = "comment_system_db"
database_id = "d1_database_id"

[env.production]
account_id = "你的Cloudflare账号ID"
