# wrangler.toml

name = "comment-system-worker"
main = "src/worker/index.js"
compatibility_date = "2023-10-01"

[vars]
TURNSTILE_SECRET_KEY = "YOUR_TURNSTILE_SECRET_KEY"
DEFAULT_TURNSTILE_SITE_KEY = "YOUR_DEFAULT_TURNSTILE_SITE_KEY"

[[kv_namespaces]]
binding = "SESSIONS"
id = "YOUR_KV_NAMESPACE_ID"

[[kv_namespaces]]
binding = "ASSETS"
id = "YOUR_ASSETS_KV_NAMESPACE_ID"

[[d1_databases]]
binding = "DB"
database_name = "YOUR_D1_DATABASE_NAME"
database_id = "YOUR_D1_DATABASE_ID"

[build]
command = "npm install && npm run build"

[env.production]
route = "your-domain.com/*"
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
